# Generated by Django 5.2.3 on 2025-08-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('mobile_no', models.CharField(max_length=20)),
                ('salary', models.FloatField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
